title: dr@fts
description: dr@fts is a simple iOS application for creating and editing notes, posts, threads, tweets, and more
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
